### ISSUE TITLE
NullPointerException: null on shutdown

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#288]
Paper dev 1547 (Spigot 1.12.2)
CrateReloaded v2.0.0-alpha7

```
[09:33:52] [Server thread/INFO]: [CrateReloaded] Disabling CrateReloaded v2.0.0-alpha7
[09:33:52] [Server thread/ERROR]: Error occurred while disabling CrateReloaded v2.0.0-alpha7 (Is it up to date?)
java.lang.NullPointerException: null
	at cratereloaded.i.o(ClaimManager.java:47) ~[?:?]
	at cratereloaded.i.cleanup(ClaimManager.java:88) ~[?:?]
	at com.hazebyte.crate.cratereloaded.CorePlugin.onDisable(CorePlugin.java:297) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1542]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[patched_1.12.2.jar:git-Paper-1542]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.12.2.jar:git-Paper-1542]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424) ~[patched_1.12.2.jar:git-Paper-1542]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) ~[patched_1.12.2.jar:git-Paper-1542]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:363) ~[patched_1.12.2.jar:git-Paper-1542]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486) ~[patched_1.12.2.jar:git-Paper-1542]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:702) ~[patched_1.12.2.jar:git-Paper-1542]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by imWillX** [comment]
Related: #283
