### ISSUE TITLE
IllegalArgumentException: Async hologram creation

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#337]
Loaded a new world with multiverse. This error occurred.

```
[01:57:01] [Craft Scheduler Thread - 696/INFO]: [CrateReloaded] Latest World Load: [darkzone]. Reloading key crates.
[01:57:01] [Craft Scheduler Thread - 696/WARN]: [CrateReloaded] Plugin CrateReloaded v2.0.2 generated an exception while executing task 102006
java.lang.IllegalArgumentException: Async hologram creation
	at com.gmail.filoghost.holographicdisplays.util.Validator.isTrue(Validator.java:27) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.DefaultBackendAPI.createHologram(DefaultBackendAPI.java:40) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.api.HologramsAPI.createHologram(HologramsAPI.java:46) ~[?:?]
	at cratereloaded.aW.c(Holographics.java:61) ~[?:?]
	at cratereloaded.F.e(BlockCrateHandler.java:248) ~[?:?]
	at cratereloaded.F.setCrate(BlockCrateHandler.java:96) ~[?:?]
	at cratereloaded.bw.parse(BlockCrateParser.java:64) ~[?:?]
	at cratereloaded.F.reload(BlockCrateHandler.java:44) ~[?:?]
	at cratereloaded.aN.run(WorldLoadListener.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.1.jar:git-Paper-373]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.1.jar:git-Paper-373]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by imWillX** [comment]
Fixed in `2.0.3`

**Comment by mibby** [comment]
When's v2.0.3 release? :)

**Comment by imWillX** [comment]
End of this weekend.
