### ISSUE TITLE
Config wont load

### ISSUE THREAD

**Issue by SimplyHate23** [Hazebyte/CrateReloaded#410]
cr reload
> [01:12:30 ERROR]: Cannot load plugins/CrateReloaded/crate.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block collection
in 'string', line 113, column 13:
- 'cmd:(/eco give %player% 15000 ...
expected <block end>, but found Scalar
in 'string', line 124, column 16:
- 'cmd:(/mp 2 %player% 1), chance:( ...
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [server.jar:git-PaperSpigot-"4c7641d"]
at cratereloaded.D.reloadConfig(Config.java:32) [CrateReloaded.jar:?]
at cratereloaded.D.getConfig(Config.java:51) [CrateReloaded.jar:?]
at cratereloaded.aH.e(CrateManager.java:408) [CrateReloaded.jar:?]
at cratereloaded.aH.d(CrateManager.java:349) [CrateReloaded.jar:?]
at cratereloaded.aH.bf(CrateManager.java:339) [CrateReloaded.jar:?]
at cratereloaded.aH.initialize(CrateManager.java:71) [CrateReloaded.jar:?]
at cratereloaded.aL.enable(Manager.java:20) [CrateReloaded.jar:?]
at cratereloaded.aL.<init>(Manager.java:13) [CrateReloaded.jar:?]
at cratereloaded.aH.<init>(CrateManager.java:62) [CrateReloaded.jar:?]
at cratereloaded.b.j(CorePlugin.java:279) [CrateReloaded.jar:?]
at cratereloaded.b.c(CorePlugin.java:160) [CrateReloaded.jar:?]
at cratereloaded.b.b(CorePlugin.java:149) [CrateReloaded.jar:?]
at cratereloaded.o.a(Reload.java:23) [CrateReloaded.jar:?]
at cratereloaded.j.onCommand(CommandManager.java:118) [CrateReloaded.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block collection
in 'string', line 113, column 13:
- 'cmd:(/eco give %player% 15000 ...
expected <block end>, but found Scalar
in 'string', line 124, column 16:
- 'cmd:(/mp 2 %player% 1), chance:( ...
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:514) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[server.jar:git-PaperSpigot-"4c7641d"]
... 26 more
> [01:12:30 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block collection
in 'string', line 113, column 13:
- 'cmd:(/eco give %player% 15000 ...
expected <block end>, but found Scalar
in 'string', line 124, column 16:
- 'cmd:(/mp 2 %player% 1), chance:( ...
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:240) [server.jar:git-PaperSpigot-"4c7641d"]
at cratereloaded.D.reloadConfig(Config.java:40) [CrateReloaded.jar:?]
at cratereloaded.D.getConfig(Config.java:51) [CrateReloaded.jar:?]
at cratereloaded.aH.e(CrateManager.java:408) [CrateReloaded.jar:?]
at cratereloaded.aH.d(CrateManager.java:349) [CrateReloaded.jar:?]
at cratereloaded.aH.bf(CrateManager.java:339) [CrateReloaded.jar:?]
at cratereloaded.aH.initialize(CrateManager.java:71) [CrateReloaded.jar:?]
at cratereloaded.aL.enable(Manager.java:20) [CrateReloaded.jar:?]
at cratereloaded.aL.<init>(Manager.java:13) [CrateReloaded.jar:?]
at cratereloaded.aH.<init>(CrateManager.java:62) [CrateReloaded.jar:?]
at cratereloaded.b.j(CorePlugin.java:279) [CrateReloaded.jar:?]
at cratereloaded.b.c(CorePlugin.java:160) [CrateReloaded.jar:?]
at cratereloaded.b.b(CorePlugin.java:149) [CrateReloaded.jar:?]
at cratereloaded.o.a(Reload.java:23) [CrateReloaded.jar:?]
at cratereloaded.j.onCommand(CommandManager.java:118) [CrateReloaded.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block collection
in 'string', line 113, column 13:
- 'cmd:(/eco give %player% 15000 ...
expected <block end>, but found Scalar
in 'string', line 124, column 16:
- 'cmd:(/mp 2 %player% 1), chance:( ...
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:514) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[server.jar:git-PaperSpigot-"4c7641d"]
... 25 more

**Comment by SimplyHate23** [comment]
https://pastebin.com/wnj16VkW

**Comment by omgitsAngus** [comment]
- 'cmd:(/es give %player% cavespider 2), chance:(99), display:(52 2 &b&l+_Cave_Spider_&rSpawner&7_[&r%chance%&7] &rPurchase_more_keys_at_&bstore.simplymc.net)''

This line ins your config has two '' at the end. 
Use this website to check where errors are in the future
https://yaml-online-parser.appspot.com/

Or use an app such as BBEdit, Notepad++ and create a .yml file, while will colour code things when you create errors. Hope this is of help.

**Comment by imWillX** [comment]
Seems like a yaml issue like QueenAngus mentioned. Closing, please reopen if the issue persist.
