### ISSUE TITLE
NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#432]
Purpur dev 348 (Paper dev 22 fork) [Spigot 1.15.1]
CrateReloaded Pro v2.0.19

@imWillX Getting this error at start-up on spigot 1.15.1.
```
[03:28:14] [Server thread/INFO]: [CrateReloaded] Enabling CrateReloaded v2.0.19
[03:28:14] [Server thread/INFO]: [CrateReloaded] Config Version: 2.X
[03:28:14] [Server thread/INFO]: [CrateReloaded] v1_15_R1
[03:28:14] [Server thread/ERROR]: Error occurred while enabling CrateReloaded v2.0.19 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
	at com.hazebyte.crate.api.util.ItemBuilder.unbreakable(ItemBuilder.java:150) ~[?:?]
	at cratereloaded.cC.a(ItemParser.java:286) ~[?:?]
	at cratereloaded.cC.T(ItemParser.java:254) ~[?:?]
	at cratereloaded.cC.R(ItemParser.java:46) ~[?:?]
	at cratereloaded.an.b(RewardParser.java:82) ~[?:?]
	at cratereloaded.an.initialize(RewardParser.java:34) ~[?:?]
	at cratereloaded.ak.a(AbstractReward.java:58) ~[?:?]
	at cratereloaded.am.<init>(CrateReward.java:18) ~[?:?]
	at cratereloaded.bA.b(CrateParser.java:218) ~[?:?]
	at cratereloaded.bA.a(CrateParser.java:94) ~[?:?]
	at cratereloaded.bA.d(CrateParser.java:55) ~[?:?]
	at cratereloaded.bA.parse(CrateParser.java:40) ~[?:?]
	at cratereloaded.K.U(CrateHandler.java:73) ~[?:?]
	at cratereloaded.K.T(CrateHandler.java:66) ~[?:?]
	at cratereloaded.K.initialize(CrateHandler.java:52) ~[?:?]
	at cratereloaded.ba.enable(Manager.java:20) ~[?:?]
	at cratereloaded.ba.<init>(Manager.java:13) ~[?:?]
	at cratereloaded.K.<init>(CrateHandler.java:38) ~[?:?]
	at com.hazebyte.crate.cratereloaded.CorePlugin.registerCrates(CorePlugin.java:201) ~[?:?]
	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:335) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:886) ~[paperclip.jar:git-Purpur-348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[03:28:14] [Server thread/INFO]: [CrateReloaded] Disabling CrateReloaded v2.0.19
[03:28:14] [Server thread/ERROR]: Error occurred while disabling CrateReloaded v2.0.19 (Is it up to date?)
java.lang.NullPointerException: null
	at com.hazebyte.crate.cratereloaded.CorePlugin.onDisable(CorePlugin.java:286) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[paperclip.jar:git-Purpur-348]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[paperclip.jar:git-Purpur-348]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:886) ~[paperclip.jar:git-Purpur-348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

Edit: Removed here? https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/530f6689ba4fea0365550cc95a50d6b76bbd9dbb#Bukkit-Patches/0016-Added-isUnbreakable-and-setUnbreakable-to-ItemMeta.patch

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/530f6689ba4fea0365550cc95a50d6b76bbd9dbb#CraftBukkit-Patches/0092-Added-isUnbreakable-and-setUnbreakable-to-ItemMeta.patch

Edit 2: It's in bukkit proper now. So you'll need to recompile and fix in source.

**Comment by imWillX** [comment]
Should be fixed. Please reopen if this still occurs.
