### ISSUE TITLE
java.lang.NoSuchMethodException: org.bukkit.inventory.meta.ItemMeta.setCustomModelData(java.lang.Integer)

### ISSUE THREAD

**Issue by FrozenBeard** [Hazebyte/CrateReloaded#439]
paper 1.12.2
CrateReloaded v2.0.21

```
[10:37:52] [Server thread/INFO]: [CrateReloaded] Enabling CrateReloaded v2.0.21
[10:37:52] [Server thread/INFO]: [CrateReloaded] Config Version: 2.X
[10:37:52] [Server thread/INFO]: [CrateReloaded] v1_12_R1
[10:37:53] [Server thread/WARN]: java.lang.NoSuchMethodException: org.bukkit.inventory.meta.ItemMeta.setCustomModelData(java.lang.Integer)
[10:37:53] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2108)
[10:37:53] [Server thread/WARN]: 	at com.hazebyte.crate.api.util.ItemBuilder.<clinit>(ItemBuilder.java:25)
[10:37:53] [Server thread/WARN]: 	at com.hazebyte.crate.api.util.ItemHelper.setName(ItemHelper.java:44)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.cC.a(ItemParser.java:284)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.cC.T(ItemParser.java:254)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.cC.R(ItemParser.java:46)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.an.b(RewardParser.java:82)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.an.initialize(RewardParser.java:34)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.ak.a(AbstractReward.java:58)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.am.<init>(CrateReward.java:18)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.bA.b(CrateParser.java:218)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:94)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.bA.d(CrateParser.java:55)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.bA.parse(CrateParser.java:40)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.K.U(CrateHandler.java:73)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.K.T(CrateHandler.java:66)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.K.initialize(CrateHandler.java:52)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.ba.enable(Manager.java:20)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.ba.<init>(Manager.java:13)
[10:37:53] [Server thread/WARN]: 	at cratereloaded.K.<init>(CrateHandler.java:38)
[10:37:53] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.registerCrates(CorePlugin.java:201)
[10:37:53] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:335)
[10:37:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:37:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[10:37:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:37:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:37:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:37:53] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:37:53] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:37:53] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:37:53] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[10:37:53] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:37:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by imWillX** [comment]
Fixed `2.0.22`
