### ISSUE TITLE
Exceptions during CR plugin enable on Paper 1.16.1

### ISSUE THREAD

**Issue by matbcvo** [Hazebyte/CrateReloaded#469]
`[23:18:58] [Server thread/INFO]: This server is running Paper version git-Paper-27 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`

```
[23:19:20] [Server thread/INFO]: [CrateReloaded] Enabling CrateReloaded v2.0.22
[23:19:20] [Server thread/INFO]: [CrateReloaded] Config Version: 2.X
[23:19:20] [Server thread/INFO]: [CrateReloaded] v1_16_R1
[23:19:20] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R1.NBTTagList.add(net.minecraft.server.v1_16_R1.NBTBase)
[23:19:20] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2108)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bZ.<clinit>(NBTEditor.java:97)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:204)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:112)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.d(CrateParser.java:55)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.parse(CrateParser.java:40)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.U(CrateHandler.java:73)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.T(CrateHandler.java:66)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.initialize(CrateHandler.java:52)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.ba.enable(Manager.java:20)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.ba.<init>(Manager.java:13)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.<init>(CrateHandler.java:38)
[23:19:20] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.registerCrates(CorePlugin.java:201)
[23:19:20] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:335)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:498)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:412)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:19:20] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[23:19:20] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R1.NBTTagByte.<init>(byte)
[23:19:20] [Server thread/WARN]: 	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
[23:19:20] [Server thread/WARN]: 	at java.base/java.lang.Class.getConstructor(Class.java:2151)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bZ.<clinit>(NBTEditor.java:173)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:204)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:112)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.d(CrateParser.java:55)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.parse(CrateParser.java:40)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.U(CrateHandler.java:73)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.T(CrateHandler.java:66)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.initialize(CrateHandler.java:52)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.ba.enable(Manager.java:20)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.ba.<init>(Manager.java:13)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.<init>(CrateHandler.java:38)
[23:19:20] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.registerCrates(CorePlugin.java:201)
[23:19:20] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:335)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:498)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:412)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:19:20] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[23:19:20] [Server thread/WARN]: java.lang.NullPointerException
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bZ.a(NBTEditor.java:442)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bZ.a(NBTEditor.java:954)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:204)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:112)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.d(CrateParser.java:55)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.bA.parse(CrateParser.java:40)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.U(CrateHandler.java:73)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.T(CrateHandler.java:66)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.initialize(CrateHandler.java:52)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.ba.enable(Manager.java:20)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.ba.<init>(Manager.java:13)
[23:19:20] [Server thread/WARN]: 	at cratereloaded.K.<init>(CrateHandler.java:38)
[23:19:20] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.registerCrates(CorePlugin.java:201)
[23:19:20] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:335)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:498)
[23:19:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:412)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[23:19:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:19:20] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[23:19:21] [Server thread/WARN]: java.lang.NullPointerException
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bZ.a(NBTEditor.java:442)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bZ.a(NBTEditor.java:954)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:204)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:112)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.d(CrateParser.java:55)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.parse(CrateParser.java:40)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.U(CrateHandler.java:73)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.T(CrateHandler.java:66)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.initialize(CrateHandler.java:52)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.ba.enable(Manager.java:20)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.ba.<init>(Manager.java:13)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.<init>(CrateHandler.java:38)
[23:19:21] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.registerCrates(CorePlugin.java:201)
[23:19:21] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:335)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:498)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:412)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:19:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[23:19:21] [Server thread/WARN]: java.lang.NullPointerException
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bZ.a(NBTEditor.java:442)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bZ.a(NBTEditor.java:954)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:204)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:112)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.d(CrateParser.java:55)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.parse(CrateParser.java:40)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.U(CrateHandler.java:73)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.T(CrateHandler.java:66)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.initialize(CrateHandler.java:52)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.ba.enable(Manager.java:20)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.ba.<init>(Manager.java:13)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.<init>(CrateHandler.java:38)
[23:19:21] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.registerCrates(CorePlugin.java:201)
[23:19:21] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:335)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:498)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:412)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:19:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[23:19:21] [Server thread/WARN]: java.lang.NullPointerException
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bZ.a(NBTEditor.java:442)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bZ.a(NBTEditor.java:954)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:204)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:112)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.d(CrateParser.java:55)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.parse(CrateParser.java:40)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.U(CrateHandler.java:73)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.T(CrateHandler.java:66)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.initialize(CrateHandler.java:52)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.ba.enable(Manager.java:20)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.ba.<init>(Manager.java:13)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.<init>(CrateHandler.java:38)
[23:19:21] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.registerCrates(CorePlugin.java:201)
[23:19:21] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:335)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:498)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:412)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:19:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[23:19:21] [Server thread/WARN]: java.lang.NullPointerException
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bZ.a(NBTEditor.java:442)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bZ.a(NBTEditor.java:954)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:204)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.a(CrateParser.java:112)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.d(CrateParser.java:55)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.bA.parse(CrateParser.java:40)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.U(CrateHandler.java:73)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.T(CrateHandler.java:66)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.initialize(CrateHandler.java:52)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.ba.enable(Manager.java:20)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.ba.<init>(Manager.java:13)
[23:19:21] [Server thread/WARN]: 	at cratereloaded.K.<init>(CrateHandler.java:38)
[23:19:21] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.registerCrates(CorePlugin.java:201)
[23:19:21] [Server thread/WARN]: 	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:335)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:498)
[23:19:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:412)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[23:19:21] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:19:21] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[23:19:21] [Server thread/INFO]: [CrateReloaded] Crate Configurations (1): crate.yml 
```

**Comment by imWillX** [comment]
The free version doesn't support 1.16.1 yet. I'll be bumping the update soon.
