### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by OmikronOverload** [Hazebyte/CrateReloaded#521]
I have no Idea why this is happening on server startup.
Its spits out errors for every item and i dont know why...
please help me ;)

java.lang.ArrayIndexOutOfBoundsException: 1
	at cratereloaded.cB.V(ItemParser.java:248) ~[?:?]
	at cratereloaded.cB.T(ItemParser.java:52) ~[?:?]
	at cratereloaded.an.b(RewardParser.java:83) ~[?:?]
	at cratereloaded.an.initialize(RewardParser.java:34) ~[?:?]
	at cratereloaded.ak.a(AbstractReward.java:58) ~[?:?]
	at cratereloaded.am.<init>(CrateReward.java:21) ~[?:?]
	at cratereloaded.bE.b(CrateParser.java:217) ~[?:?]
	at cratereloaded.bE.a(CrateParser.java:94) ~[?:?]
	at cratereloaded.bE.c(CrateParser.java:55) ~[?:?]
	at cratereloaded.bE.parse(CrateParser.java:40) ~[?:?]
	at cratereloaded.K.Q(CrateHandler.java:79) ~[?:?]
	at cratereloaded.K.P(CrateHandler.java:72) ~[?:?]
	at cratereloaded.K.initialize(CrateHandler.java:58) ~[?:?]
	at cratereloaded.bf.enable(Manager.java:20) ~[?:?]
	at cratereloaded.bf.<init>(Manager.java:13) ~[?:?]
	at cratereloaded.K.<init>(CrateHandler.java:43) ~[?:?]
	at com.hazebyte.crate.cratereloaded.CorePlugin.registerCrates(CorePlugin.java:206) ~[?:?]
	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:336) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[18:47:46] [Server thread/INFO]: [CrateReloaded] Disabling CrateReloaded v2.0.23
[18:47:46] [Server thread/ERROR]: Error occurred while disabling CrateReloaded v2.0.23 (Is it up to date?)
java.lang.NullPointerException: null
	at com.hazebyte.crate.cratereloaded.CorePlugin.onDisable(CorePlugin.java:287) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper-1.16.3-b253.jar:git-Paper-253]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by imWillX** [comment]
Need more information. Please open a new issue and provide your crate configuration.
