### ISSUE TITLE
[Error] Hologram nbt issue?

### ISSUE THREAD

**Issue by Disorbs** [Hazebyte/CrateReloaded#548]
So not sure what's going on or if its just not supported or something on my side but I receive this error at the start of the server but the crates itself works it just looks spamy would love to fix it.

I have holographic displays installed latest update
paper 1.18.1

```
[CrateReloaded] Hologram Provider: HolographicDisplays
[13:07:48] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.nbt.NBTTagCompound.get(java.lang.String)
[13:07:48] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[13:07:48] [Server thread/WARN]: 	at CrateReloaded.jar//cratereloaded.cj.<clinit>(NBTEditor.java:136)
[13:07:48] [Server thread/WARN]: 	at CrateReloaded.jar//cratereloaded.bN.a(CrateParser.java:221)
[13:07:48] [Server thread/WARN]: 	at CrateReloaded.jar//cratereloaded.bN.a(CrateParser.java:131)
```

Full error: https://paste.md-5.net/yobuhokiye.md

EDIT: I think I'm also not receiving my keys I get a crate with some language prefix in it. (Crate: Voting, Section: Voting.Item)

**Comment by imWillX** [comment]
NBT has been removed. Please let me know if this issue still occurs.
