### ISSUE TITLE
[Error] java.lang.NoClassDefFoundError: org/bukkit/Particle

### ISSUE THREAD

**Issue by youngwithlag** [Hazebyte/CrateReloaded#552]
When I try to place the foodChest, the error appears in the console.

```
[19:15:03] [Server thread/INFO]: Estebannsz issued server command: /cr give to Estebannsz foodchest
[19:15:16] [luckperms-command-executor/INFO]: [0;37;22m[[0;36;1m[21mL[0;36;22m[21mP[0;37;22m][m [0;32;1mSet [0;36;1m*[0;32;1m to [0;36;1mtrue[0;32;1m for [0;36;1mestebannsz[0;32;1m in context [0;33;1mglobal[0;32;1m.[m
[19:15:21] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to CrateReloaded v2.0.25
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:490) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:475) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:128) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:161) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:842) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:67) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:6) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:784) [NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723) [NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/Particle
	at de.slikey.effectlib.EffectManager.setField(EffectManager.java:472) ~[?:?]
	at de.slikey.effectlib.EffectManager.getEffect(EffectManager.java:237) ~[?:?]
	at de.slikey.effectlib.EffectManager.getEffect(EffectManager.java:341) ~[?:?]
	at crate.aa.a(UserCrate.java:76) ~[?:?]
	at crate.aa.runEffect(UserCrate.java:251) ~[?:?]
	at crate.aG.a(SupplyCrate.java:42) ~[?:?]
	at crate.aa.open(UserCrate.java:177) ~[?:?]
	at crate.bp.a(SupplyCrateListener.java:42) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[NachoSpigot.jar:git-NachoSpigot-"74ed0ea"]
	... 19 more
```

**Server details:**
Fork: NachoSpigot
Java version: 17
Minecraft version: 1.8.9
CrateReloaded version: the last to date
Plugins (10): LuckPerms, WorldEdit, PlaceholderAPI, Multiverse-Core, WorldGuard, Scoreboard-revision, DeluxeMenus, CMILib, CMI, CrateReloaded

**Comment by imWillX** [comment]
Fixed `2.1.5`
