### ISSUE TITLE
IllegalStateException: We don't have CustomModelData! Check hasCustomModelData first!

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#554]
Paper 1.18.2
CrateReloaded Pro v2.0.38

@imWillX Noticed this error after updating from 2.0.37 to 2.0.38. Possibly caused by this fix? https://github.com/Hazebyte/CrateReloaded/issues/525

```
[05:36:31] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[05:36:31] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[05:36:31] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//com.hazebyte.crate.api.util.ItemBuilder.getCustomModelData(ItemBuilder.java:217)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//crate.cH.n(ItemParser.java:100)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//crate.ay.serialize(AbstractReward.java:70)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//com.hazebyte.crate.api.crate.Claim.lambda$serialize$0(Claim.java:69)
[05:36:31] [Server thread/WARN]: 	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//com.hazebyte.crate.api.crate.Claim.serialize(Claim.java:68)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//crate.y.a(ClaimManager.java:149)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//crate.B.a(CrateCommand.java:287)
[05:36:31] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[05:36:31] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//com.hazebyte.libs.aikar.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//com.hazebyte.libs.aikar.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//com.hazebyte.libs.aikar.acf.BaseCommand.execute(BaseCommand.java:513)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//com.hazebyte.libs.aikar.acf.RootCommand.execute(RootCommand.java:99)
[05:36:31] [Server thread/WARN]: 	at CrateReloaded.jar//com.hazebyte.libs.aikar.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[05:36:31] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[05:36:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[05:36:31] [Server thread/WARN]: 	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:959)
[05:36:31] [Server thread/WARN]: 	at EnjinMinecraftPlugin.jar//com.enjin.bukkit.EnjinMinecraftPlugin.lambda$dispatchConsoleCommand$1(EnjinMinecraftPlugin.java:402)
[05:36:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[05:36:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[05:36:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1558)
[05:36:31] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[05:36:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1482)
[05:36:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[05:36:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[05:36:31] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[05:36:31] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: We don't have CustomModelData! Check hasCustomModelData first!
[05:36:31] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
[05:36:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaItem.getCustomModelData(CraftMetaItem.java:1080)
[05:36:31] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[05:36:31] [Server thread/WARN]: 	... 28 more
[05:36:31] [Server thread/INFO]: CMD: truefalse0
[05:36:31] [Server thread/INFO]: Crate » Lord_Khaine is not online. They may claim their crate via '/cr claim'.
[05:36:31] [Server thread/INFO]: Crate » You have given a VoterCrate to Lord_Khaine. STATUS: SENT TO CLAIM.
```

The console command ran is ``/cr give to <player> <crate> <amount>`` that occurs when players vote.

**Comment by imWillX** [comment]
Thanks for the report @mibby. Will be fixed in `2.0.39`.
