### ISSUE TITLE
Uncaught exception java.lang.NoSuchMethodException: crate.cg

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#564]
Updated to v2.1.0-alpha and this error occurs. Downgrading to v2.0.39 all is fine.

```
[05:57:57] [Server thread/INFO]: [CrateReloaded] Provider: HolographicDisplays
[05:57:57] [Server thread/ERROR]: [CrateReloaded] Uncaught exception
java.lang.NoSuchMethodException: crate.cg.<init>(org.bukkit.plugin.java.JavaPlugin)
	at java.lang.Class.getConstructor0(Class.java:3617) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2303) ~[?:?]
	at crate.cb.y(ProviderSelector.java:42) ~[CrateReloaded.jar:?]
	at com.hazebyte.crate.cratereloaded.CorePlugin.a(CorePlugin.java:250) ~[CrateReloaded.jar:?]
	at com.hazebyte.crate.cratereloaded.CorePlugin.Y(CorePlugin.java:274) ~[CrateReloaded.jar:?]
	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:176) ~[CrateReloaded.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
[05:58:07] [Server thread/ERROR]: Error occurred while disabling CrateReloaded v2.1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "crate.ac.aS()" because "this.ax" is null
	at com.hazebyte.crate.cratereloaded.CorePlugin.onDisable(CorePlugin.java:128) ~[CrateReloaded.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:585) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:562) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:530) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:946) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:821) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1259) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1770]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by imWillX** [comment]
Fixed in latest 2.1.0 hotfix.
