### ISSUE TITLE
Plugin CrateReloaded v2.1.1 has failed to register events for class crate.aM because org/bukkit/Particle does not exist.

### ISSUE THREAD

**Issue by Squidben1** [Hazebyte/CrateReloaded#567]
[10:12:39 INFO]: [CrateReloaded] Enabling CrateReloaded v2.1.1
[10:12:39 ERROR]: [CrateReloaded] Plugin CrateReloaded v2.1.1 has failed to register events for class crate.aM because org/bukkit/Particle does not exist.
[10:12:39 INFO]: [CrateReloaded] Provider: HolographicDisplays
[10:12:39 INFO]: [CrateReloaded] Provider: Vault
[10:12:40 ERROR]: Error occurred while enabling CrateReloaded v2.1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
        at de.slikey.effectlib.EffectManager.setField(EffectManager.java:472) ~[?:?]
        at de.slikey.effectlib.EffectManager.getEffect(EffectManager.java:237) ~[?:?]
        at de.slikey.effectlib.EffectManager.getEffect(EffectManager.java:341) ~[?:?]
        at crate.bY.a(CrateParser.java:151) ~[?:?]
        at crate.bY.b(CrateParser.java:67) ~[?:?]
        at crate.bY.bq(CrateParser.java:52) ~[?:?]
        at crate.ad.aq(CrateHandler.java:78) ~[?:?]
        at crate.ad.ap(CrateHandler.java:71) ~[?:?]
        at crate.ad.ac(CrateHandler.java:57) ~[?:?]
        at crate.bz.ab(Manager.java:20) ~[?:?]
        at crate.bz.<init>(Manager.java:13) ~[?:?]
        at crate.ad.<init>(CrateHandler.java:42) ~[?:?]
        at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:193) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[WineSpigot-V1.7.2.jar:1_8_R3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:321) [WineSpigot-V1.7.2.jar:1_8_R3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) [WineSpigot-V1.7.2.jar:1_8_R3]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:385) [WineSpigot-V1.7.2.jar:1_8_R3]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:320) [WineSpigot-V1.7.2.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:469) [WineSpigot-V1.7.2.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:433) [WineSpigot-V1.7.2.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:388) [WineSpigot-V1.7.2.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:268) [WineSpigot-V1.7.2.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:665) [WineSpigot-V1.7.2.jar:1_8_R3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:95) ~[WineSpigot-V1.7.2.jar:1_8_R3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[WineSpigot-V1.7.2.jar:1_8_R3]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 24 more
[10:12:40 INFO]: [CrateReloaded] Disabling CrateReloaded v2.1.1
[10:12:40 ERROR]: Error occurred while disabling CrateReloaded v2.1.1 (Is it up to date?)
java.lang.NullPointerException
        at com.hazebyte.crate.cratereloaded.CorePlugin.onDisable(CorePlugin.java:141) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[WineSpigot-V1.7.2.jar:1_8_R3]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:349) [WineSpigot-V1.7.2.jar:1_8_R3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) [WineSpigot-V1.7.2.jar:1_8_R3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) [WineSpigot-V1.7.2.jar:1_8_R3]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:385) [WineSpigot-V1.7.2.jar:1_8_R3]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:320) [WineSpigot-V1.7.2.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:469) [WineSpigot-V1.7.2.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:433) [WineSpigot-V1.7.2.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:388) [WineSpigot-V1.7.2.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:268) [WineSpigot-V1.7.2.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:665) [WineSpigot-V1.7.2.jar:1_8_R3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by imWillX** [comment]
This is fixed in `2.1.5`. Let me know if there are any issues.
