### ISSUE TITLE
Wont boot. java.lang.NumberFormatException: For input string: "4}"

### ISSUE THREAD

**Issue by TomLewis** [Hazebyte/CrateReloaded#582]
Tried to update to 2.2.1 from 2.1.12 on Purpur 1.18.2, throws an exception at boot. plugin fails to load.

```
[10:32:38] [Server thread/INFO]: [CrateReloaded] Enabling CrateReloaded v2.2.1
[10:32:38] [Server thread/INFO]: [CrateReloaded] Spigot Version: 1_18_R2
[10:32:39] [Server thread/INFO]: [CrateReloaded] Provider: CMI
[10:32:39] [Server thread/INFO]: [CrateReloaded] Provider: Vault
[10:32:39] [Server thread/INFO]: [CrateReloaded] Provider: EffectLib
[10:32:39] [Server thread/ERROR]: [CrateReloaded] Uncaught exception. Please report this to the author...
java.lang.NumberFormatException: For input string: "4}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Short.parseShort(Short.java:137) ~[?:?]
	at java.lang.Short.parseShort(Short.java:163) ~[?:?]
	at crate.dC.M(ItemParser.java:76) ~[CrateReloaded_2.2.1.jar:?]
	at crate.aU.b(RewardParser.java:92) ~[CrateReloaded_2.2.1.jar:?]
	at crate.aU.<init>(RewardParser.java:26) ~[CrateReloaded_2.2.1.jar:?]
	at crate.cj.<init>(RewardImpl.java:41) ~[CrateReloaded_2.2.1.jar:?]
	at crate.cl.a(CrateParser.java:261) ~[CrateReloaded_2.2.1.jar:?]
	at crate.cl.b(CrateParser.java:125) ~[CrateReloaded_2.2.1.jar:?]
	at crate.cl.b(CrateParser.java:73) ~[CrateReloaded_2.2.1.jar:?]
	at crate.cl.br(CrateParser.java:58) ~[CrateReloaded_2.2.1.jar:?]
	at crate.ao.ak(CrateHandler.java:64) ~[CrateReloaded_2.2.1.jar:?]
	at crate.ao.aj(CrateHandler.java:56) ~[CrateReloaded_2.2.1.jar:?]
	at crate.ao.<init>(CrateHandler.java:48) ~[CrateReloaded_2.2.1.jar:?]
	at com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:199) ~[CrateReloaded_2.2.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:32:39] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "4}"
[10:32:39] [Server thread/WARN]: 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[10:32:39] [Server thread/WARN]: 	at java.base/java.lang.Integer.parseInt(Integer.java:668)
[10:32:39] [Server thread/WARN]: 	at java.base/java.lang.Short.parseShort(Short.java:137)
[10:32:39] [Server thread/WARN]: 	at java.base/java.lang.Short.parseShort(Short.java:163)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.dC.M(ItemParser.java:76)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.aU.b(RewardParser.java:92)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.aU.<init>(RewardParser.java:26)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.cj.<init>(RewardImpl.java:41)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.cl.a(CrateParser.java:261)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.cl.b(CrateParser.java:125)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.cl.b(CrateParser.java:73)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.cl.br(CrateParser.java:58)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.ao.ak(CrateHandler.java:64)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.ao.aj(CrateHandler.java:56)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//crate.ao.<init>(CrateHandler.java:48)
[10:32:39] [Server thread/WARN]: 	at CrateReloaded_2.2.1.jar//com.hazebyte.crate.cratereloaded.CorePlugin.onEnable(CorePlugin.java:199)
[10:32:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:32:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[10:32:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[10:32:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[10:32:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[10:32:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[10:32:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[10:32:39] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[10:32:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[10:32:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[10:32:39] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by scottyboii** [comment]
Please attach your crate file(s)

**Comment by TomLewis** [comment]
Crates work fine and have done until this update.

**Comment by imWillX** [comment]
@TomLewis we recently have had an update with breaking changes. https://www.spigotmc.org/resources/pro-crate-reloaded-mystery-crate-1-8-1-19-x.3663/update?update=487696

**Comment by TomLewis** [comment]
I don't use nbt or CustomModelData which was listed as the breaking changes.

**Comment by imWillX** [comment]
Could you DM me your crate on discord? It’ll help debug this quicker.

**Comment by imWillX** [comment]
@TomLewis Do you use durability values? Sorry, I didn't include this in the update logs but damage is moved to a flag.

Before: `dirt:123 1`

e.g. `dirt 1 durability:123`

**Comment by TomLewis** [comment]
Ahh I may do! That may be it then! I will look over my files when I'm home tonight! Thank you

**Comment by scottyboii** [comment]
@TomLewis Did you manage to solve this?

**Comment by TomLewis** [comment]
I haven't had time to look over all my configs, I just wont be able to update if it breaks everything and there's no clear message that tells me exactly what needs to change.

It is insnae we have to go back and search through all files, why it wouldn't just output the error instead of entirely killing itself. Very poor implementation.

**Comment by scottyboii** [comment]
If you want to send over your crate files to one of us, we can take a look for you and let you know!

**Comment by imWillX** [comment]
@TomLewis I'll fix the issue where the parser crashes rather than outputs an error.

I knew this was going to be a breaking change thus the major version update. I can add backward compatibility.

**Comment by TomLewis** [comment]
The latest version seems to boot fine now! And it gives an error message:
```
[10:32:30] [Server thread/INFO]: [CrateReloaded] Found NBT in deprecated format. This will not be parsed: [{CustomModelData:4}]
[10:32:30] [Server thread/INFO]: [CrateReloaded] Found NBT in deprecated format. This will not be parsed: [{CustomModelData:4}]
```

So I searched through all my files and found this! Which is weird as I dont have a RP at present on the server and no need for this! Very odd! At least I was able to find this deep in my crates files from the error message now! If you wish to improve on it further you could output the crate name/line number for anyone else that may not know how to search files for text.

**Comment by scottyboii** [comment]
Did you manage to solve this, @TomLewis?

**Comment by TomLewis** [comment]
@scottyboii yeah! So if you use VScode you can right click on the folder of all your crate files and search all files, I used the text that was shown in the startup error to search all my crate files for the "legacy" broken bits across all crates, vscode then lets you click and takes you to the line where it is, so you dont have to spend ages searching through each doc one by one!

**Comment by scottyboii** [comment]
Awesome, glad you fixed it!
