### ISSUE TITLE
Game breaking "Unable to parse claim data for" all of a sudden out of nowhere.

### ISSUE THREAD

**Issue by TomLewis** [Hazebyte/CrateReloaded#585]
I released a new Crate today, out of nowhere peolpe are trying to use keys and some peolpe are just having their key used up, and not actually being used, but its throwing an error in console!

The only thing I can think that's different with this crate is that the key uses a gradient.

`item: TRIPWIRE_HOOK 1 name:&8[#FFE259✿#F5E356_#EAE354S#E0E451p#D6E54Fr#CBE54Ci#C1E64An#B7E647g#ADE745_#A2E842K#98E83Fe#8EE93Dy#83EA3A_#79EA382#6FEB350#64EB332#5AEC303&8] lore:&7Right_click_the_&eSpring_Treasure_Chest_&7to_win_a_prize!|&7See_&9/treasure&7_for_more_info`

This is major as this is now live, and Ive never had this issue before with crates, what is going on?

```
[22:24:57] [Server thread/INFO]: Coldat issued server command: /crate claim
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: [CrateReloaded] Unable to parse claim data for 1b17a775-df6e-455d-bf47-52a9308a9709: 
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "06f2f2f0-31bb-4bb6-bf99-13d88e8f8e50"
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at CrateReloaded_2.2.4.jar//crate.V.b(YamlClaimStorage.java:120)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: Caused by: java.lang.NumberFormatException: For input string: "06f2f2f0-31bb-4bb6-bf99-13d88e8f8e50"
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.lang.Long.parseLong(Long.java:711)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.lang.Long.parseLong(Long.java:836)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at CrateReloaded_2.2.4.jar//crate.R.a(V1YamlClaimLineParser.java:34)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at CrateReloaded_2.2.4.jar//crate.R.apply(V1YamlClaimLineParser.java:21)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at CrateReloaded_2.2.4.jar//crate.Q.a(V1ToV2.java:30)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	at CrateReloaded_2.2.4.jar//crate.V.b(YamlClaimStorage.java:94)
[22:24:57] [ForkJoinPool.commonPool-worker-1/WARN]: 	... 7 more
```

```
06f2f2f0-31bb-4bb6-bf99-13d88e8f8e50:
  timestamp: '1672779061632'
  player: 1b17a775-df6e-455d-bf47-52a9308a9709
  rewards:
  - item:(CARVED_PUMPKIN 1 name:Sticky_Pumpkin_21), chance:(0.0), display:(CARVED_PUMPKIN
    1 name:Sticky_Pumpkin_21)
```

**Comment by TomLewis** [comment]
Bump @imWillX

**Comment by imWillX** [comment]
@TomLewis Taking a look
